name: slikker_kit
description: Slikker Kit is a Flutter package which provides Slikker Design System components.

version: 1.1.0-alpha.35

homepage: https://github.com/AlexBesida/slikker_kit#readme
repository: https://github.com/AlexBesida/slikker_kit

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.0.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test: ^1.22.0

flutter:
  fonts:
  - family: SlikkerIcons
    fonts:
      - asset: fonts/SlikkerIcons.ttf
